
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    volumes:
      - .:/index
      - /index/node_modules
    networks:
      - shared_network
networks:
  shared_network:
    external: true
